### ISSUE TITLE
Adding / editing events

### ISSUE THREAD

**Issue by beerscrub** [BusfyJan/ArticlesEventsCakeWeb#14]
It is not possible to add/edit event because of datetime fields validation.

**Comment by BusfyJan** [comment]
$ is not a function --> jQuery import moved to the head section for Author template

Not resolved problem --> datepicker not showing how it is supposed to

**Comment by BusfyJan** [comment]
resolved - see 52db70eca7cfa0dd3f62b2e965d6a7202acd7413
